import '@/styles/globals.css';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import { Providers } from '@/providers';

const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tribal Health',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${manrope.className} `}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
