import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import { Providers } from '@/providers';

const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({ subsets: ['latin'] });

//view imports
import { SideBar } from '@/components/ui/sidebar';
import { Header } from '@/components/ui/header';

export const metadata: Metadata = {
  title: 'Tribal Health',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${manrope.className}`}>
        <div className='w-full flex'>
          <SideBar className='w-[280px]' />
          <div className='flex-1 flex flex-col'>
            {/* Container for Header and Providers */}

            <Header />
            <div className='flex-1'>
              <Providers>{children}</Providers>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
